version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app    # Mount entire project directory
    command: bash -c "pip install -e . && uvicorn mta_api.main:app --host 0.0.0.0 --port 8000 --reload"